// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njegfcdfrwyvjexjkfnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qZWdmY2Rmcnd5dmpleGprZm5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTQ0ODEsImV4cCI6MjA3MzU3MDQ4MX0.sYCXBc5Q9ZLevU66PMlVrMBT5dHlxA7aDMdkPnPTs4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});